#!/usr/bin/env python3
"""
Fixtures for GithubOrgClient integration tests.
"""

# Payload for the 'google' organization
org_payload_google = {
    "login": "google",
    "id": 1342004,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
    "repos_url": "https://api.github.com/orgs/google/repos",
    "name": "Google",
    "company": "Google",
    "blog": "https://opensource.google/",
    "location": "Mountain View, CA",
    "email": None,
    "is_verified": True,
    "has_organization_projects": True,
    "has_repository_projects": True,
    "public_repos": 1000,
    "public_gists": 0,
    "followers": 100000,
    "following": 0,
    "html_url": "https://github.com/google",
    "type": "Organization",
    "created_at": "2011-03-24T18:03:00Z",
    "updated_at": "2023-01-01T00:00:00Z"
}

# Repositories payload for the 'google' organization
repos_payload_google = [
    {
        "id": 1,
        "name": "google-cloud-sdk",
        "private": False,
        "owner": {"login": "google"},
        "html_url": "https://github.com/google/google-cloud-sdk",
        "description": "Google Cloud SDK",
        "fork": False,
        "url": "https://api.github.com/repos/google/google-cloud-sdk",
        "created_at": "2014-04-10T00:00:00Z",
        "updated_at": "2023-07-19T00:00:00Z",
        "pushed_at": "2023-07-19T00:00:00Z",
        "git_url": "git://github.com/google/google-cloud-sdk.git",
        "ssh_url": "git@github.com:google/google-cloud-sdk.git",
        "clone_url": "https://github.com/google/google-cloud-sdk.git",
        "svn_url": "https://github.com/google/google-cloud-sdk",
        "homepage": None,
        "size": 10000,
        "stargazers_count": 50000,
        "watchers_count": 50000,
        "language": "Python",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 10000,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 100,
        "license": {"key": "apache-2.0", "name": "Apache License 2.0"},
        "allow_forking": True,
        "is_template": False,
        "web_commit_signoff_required": False,
        "topics": [],
        "visibility": "public",
        "forks": 10000,
        "open_issues": 100,
        "watchers": 50000,
        "default_branch": "main"
    },
    {
        "id": 2,
        "name": "go-cloud",
        "private": False,
        "owner": {"login": "google"},
        "html_url": "https://github.com/google/go-cloud",
        "description": "Go Cloud is an open source library and tools for open cloud development.",
        "fork": False,
        "url": "https://api.github.com/repos/google/go-cloud",
        "created_at": "2018-07-25T00:00:00Z",
        "updated_at": "2023-07-19T00:00:00Z",
        "pushed_at": "2023-07-19T00:00:00Z",
        "git_url": "git://github.com/google/go-cloud.git",
        "ssh_url": "git@github.com:google/go-cloud.git",
        "clone_url": "https://github.com/google/go-cloud.git",
        "svn_url": "https://github.com/google/go-cloud",
        "homepage": "https://gocloud.dev",
        "size": 5000,
        "stargazers_count": 15000,
        "watchers_count": 15000,
        "language": "Go",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 2000,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 50,
        "license": {"key": "apache-2.0", "name": "Apache License 2.0"},
        "allow_forking": True,
        "is_template": False,
        "web_commit_signoff_required": False,
        "topics": ["go", "cloud"],
        "visibility": "public",
        "forks": 2000,
        "open_issues": 50,
        "watchers": 15000,
        "default_branch": "master"
    },
    {
        "id": 3,
        "name": "guava",
        "private": False,
        "owner": {"login": "google"},
        "html_url": "https://github.com/google/guava",
        "description": "Google core libraries for Java",
        "fork": False,
        "url": "https://api.github.com/repos/google/guava",
        "created_at": "2010-06-08T00:00:00Z",
        "updated_at": "2023-07-19T00:00:00Z",
        "pushed_at": "2023-07-19T00:00:00Z",
        "git_url": "git://github.com/google/guava.git",
        "ssh_url": "git@github.com:google/guava.git",
        "clone_url": "https://github.com/google/guava.git",
        "svn_url": "https://github.com/google/guava",
        "homepage": "https://github.com/google/guava",
        "size": 20000,
        "stargazers_count": 40000,
        "watchers_count": 40000,
        "language": "Java",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 8000,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 80,
        "license": {"key": "apache-2.0", "name": "Apache License 2.0"},
        "allow_forking": True,
        "is_template": False,
        "web_commit_signoff_required": False,
        "topics": ["java", "libraries"],
        "visibility": "public",
        "forks": 8000,
        "open_issues": 80,
        "watchers": 40000,
        "default_branch": "master"
    },
    {
        "id": 4,
        "name": "protobuf",
        "private": False,
        "owner": {"login": "google"},
        "html_url": "https://github.com/google/protobuf",
        "description": "Protocol Buffers - Google's data interchange format",
        "fork": False,
        "url": "https://api.github.com/repos/google/protobuf",
        "created_at": "2008-07-10T00:00:00Z",
        "updated_at": "2023-07-19T00:00:00Z",
        "pushed_at": "2023-07-19T00:00:00Z",
        "git_url": "git://github.com/google/protobuf.git",
        "ssh_url": "git@github.com:google/protobuf.git",
        "clone_url": "https://github.com/google/protobuf.git",
        "svn_url": "https://github.com/google/protobuf",
        "homepage": "https://developers.google.com/protocol-buffers/",
        "size": 30000,
        "stargazers_count": 60000,
        "watchers_count": 60000,
        "language": "C++",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 12000,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 120,
        "license": {"key": "bsd-3-clause", "name": "BSD 3-Clause \"New\" or \"Revised\" License"},
        "allow_forking": True,
        "is_template": False,
        "web_commit_signoff_required": False,
        "topics": ["protocol-buffers", "serialization"],
        "visibility": "public",
        "forks": 12000,
        "open_issues": 120,
        "watchers": 60000,
        "default_branch": "main"
    },
    {
        "id": 5,
        "name": "no-license-repo",
        "private": False,
        "owner": {"login": "google"},
        "html_url": "https://github.com/google/no-license-repo",
        "description": "A repository without a license",
        "fork": False,
        "url": "https://api.github.com/repos/google/no-license-repo",
        "created_at": "2020-01-01T00:00:00Z",
        "updated_at": "2023-07-19T00:00:00Z",
        "pushed_at": "2023-07-19T00:00:00Z",
        "git_url": "git://github.com/google/no-license-repo.git",
        "ssh_url": "git@github.com:google/no-license-repo.git",
        "clone_url": "https://github.com/google/no-license-repo.git",
        "svn_url": "https://github.com/google/no-license-repo",
        "homepage": None,
        "size": 100,
        "stargazers_count": 10,
        "watchers_count": 10,
        "language": "Python",
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "forks_count": 5,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 1,
        "license": None,  # Explicitly no license
        "allow_forking": True,
        "is_template": False,
        "web_commit_signoff_required": False,
        "topics": [],
        "visibility": "public",
        "forks": 5,
        "open_issues": 1,
        "watchers": 10,
        "default_branch": "main"
    }
]

# Expected repository names for 'google'
expected_repos_google = [
    "google-cloud-sdk",
    "go-cloud",
    "guava",
    "protobuf",
    "no-license-repo"
]

# Expected Apache-2.0 licensed repository names for 'google'
apache2_repos_google = [
    "google-cloud-sdk",
    "go-cloud",
    "guava"
]

# Payload for the 'abc' organization (example for parameterization)
org_payload_abc = {
    "login": "abc",
    "id": 5678,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjU2Nzg=",
    "repos_url": "https://api.github.com/orgs/abc/repos",
    "name": "ABC Corp",
    "company": "ABC Inc.",
    "blog": None,
    "location": "Anywhere, USA",
    "email": None,
    "is_verified": False,
    "has_organization_projects": True,
    "has_repository_projects": True,
    "public_repos": 2,
    "public_gists": 0,
    "followers": 10,
    "following": 0,
    "html_url": "https://github.com/abc",
    "type": "Organization",
    "created_at": "2020-01-01T00:00:00Z",
    "updated_at": "2023-01-01T00:00:00Z"
}

# Repositories payload for the 'abc' organization
repos_payload_abc = [
    {
        "id": 101,
        "name": "abc-project-x",
        "private": False,
        "owner": {"login": "abc"},
        "html_url": "https://github.com/abc/abc-project-x",
        "description": "Project X by ABC",
        "fork": False,
        "url": "https://api.github.com/repos/abc/abc-project-x",
        "license": {"key": "mit", "name": "MIT License"},
    },
    {
        "id": 102,
        "name": "abc-project-y",
        "private": False,
        "owner": {"login": "abc"},
        "html_url": "https://github.com/abc/abc-project-y",
        "description": "Project Y by ABC",
        "fork": False,
        "url": "https://api.github.com/repos/abc/abc-project-y",
        "license": {"key": "apache-2.0", "name": "Apache License 2.0"},
    }
]

# Expected repository names for 'abc'
expected_repos_abc = ["abc-project-x", "abc-project-y"]

# Expected Apache-2.0 licensed repository names for 'abc'
apache2_repos_abc = ["abc-project-y"]


# Combine fixtures for parameterized_class
fixtures = [
    {
        "org_payload": org_payload_google,
        "repos_payload": repos_payload_google,
        "expected_repos": expected_repos_google,
        "apache2_repos": apache2_repos_google,
    },
    {
        "org_payload": org_payload_abc,
        "repos_payload": repos_payload_abc,
        "expected_repos": expected_repos_abc,
        "apache2_repos": apache2_repos_abc,
    },
]
