#!/bin/bash
set -e

echo "🚀 Deploying Blue version..."
kubectl apply -f blue_deployment.yaml

echo "🚀 Deploying Green version..."
kubectl apply -f green_deployment.yaml

echo "🔍 Checking logs for Green version..."
kubectl logs -l app=django,version=green --tail=50

echo "⚡ Switching Service from Blue to Green..."
kubectl apply -f kubeservice.yaml

echo "✅ Blue-Green Deployment complete!"
